xilinx-bootbin_1.0.bb: Fix race condition in create_bif
This problem was introduced by a622db96dd962c9a5ceb999ccd99da7ad7a40faf

From documentation of DEPENDS variable:
[...]This mechanism is implemented by having do_configure depend on the
do_populate_sysroot task of each recipe listed in DEPENDS[...]

This is why the xilinx-bootbin:do_configure task can start as soon as
(for example) bitstream-extraction:do_populate_sysroot succeeds.
Consequently, bitstream-extraction:do_deploy may not have run yet when
xilinx-bootbin:do_configure (and create_bif) runs. The result is a
python stack trace pointing at line 'if os.stat(imagestr).st_size == 0:'
with an error which looks like this:

Exception: FileNotFoundError: [Errno 2] No such file or directory:
'/builds/yocto/mymachine/tmp/deploy/images/mymachine/download-mymachine.bit'

A re-attempt of the build will ultimately succeed as the do_deploy of
each dependency is spawned in parallel and get to do their job.

Targeting the "do_deploy" steps specifically fixes the problem
completely.

The ':do_deploy' is added to the BIF_PARTITION_DEPENDS, otherwise, it
would force the files assigned to BIF_PARTITION_IMAGE to be in the
DEPLOY_DIR.

Signed-off-by: Jean-Francois Dagenais <jeff.dagenais@gmail.com>
Signed-off-by: Manjukumar Matha <manjukumar.harthikote-matha@xilinx.com>