openamp-fw.inc: Fix relative path symlink issue
By default -fcanon-prefix-map is enabled in YP but If one is mixing
absolute paths and some are canonical and others aren't then it fails
to build with gcc-13+.

/scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/openamp-fw-rpc-demo/2024.2+git/recipe-sysroot-native/Vitis/2024.2/gnu/armr5/lin/gcc-arm-none-eabi/x86_64-oesdk-linux/usr/bin/arm-xilinx-eabi/arm-xilinx-eabi-ld.real: rpc_demo.o: in function `app':
| rpc_demo.c:(.text+0x70): undefined reference to `rpmsg_rpc_init'
| /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/openamp-fw-rpc-demo/2024.2+git/recipe-sysroot-native/Vitis/2024.2/gnu/armr5/lin/gcc-arm-none-eabi/x86_64-oesdk-linux/usr/bin/arm-xilinx-eabi/arm-xilinx-eabi-ld.real: rpc_demo.c:(.text+0x7c): undefined reference to `rpmsg_set_default_rpc'
| /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/openamp-fw-rpc-demo/2024.2+git/recipe-sysroot-native/Vitis/2024.2/gnu/armr5/lin/gcc-arm-none-eabi/x86_64-oesdk-linux/usr/bin/arm-xilinx-eabi/arm-xilinx-eabi-ld.real: rpc_demo.c:(.text+0x298): undefined reference to `rpmsg_rpc_send'
| /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/openamp-fw-rpc-demo/2024.2+git/recipe-sysroot-native/Vitis/2024.2/gnu/armr5/lin/gcc-arm-none-eabi/x86_64-oesdk-linux/usr/bin/arm-xilinx-eabi/arm-xilinx-eabi-ld.real: rpc_demo.c:(.text+0x2a8): undefined reference to `rpmsg_rpc_release'
| /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/openamp-fw-rpc-demo/2024.2+git/recipe-sysroot-native/Vitis/2024.2/gnu/armr5/lin/gcc-arm-none-eabi/x86_64-oesdk-linux/usr/bin/arm-xilinx-eabi/arm-xilinx-eabi-ld.real: /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/openamp-fw-rpc-demo/2024.2+git/recipe-sysroot-native/Vitis/2024.2/gnu/armr5/lin/gcc-arm-none-eabi/bin/../armrm-xilinx-eabi/usr/lib/thumb/v7+fp/hard/libc.a(lib_a-writer.o): in function `_write_r':
| (.text+0x1a): undefined reference to `_write'
| /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/openamp-fw-rpc-demo/2024.2+git/recipe-sysroot-native/Vitis/2024.2/gnu/armr5/lin/gcc-arm-none-eabi/x86_64-oesdk-linux/usr/bin/arm-xilinx-eabi/arm-xilinx-eabi-ld.real: /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/openamp-fw-rpc-demo/2024.2+git/recipe-sysroot-native/Vitis/2024.2/gnu/armr5/lin/gcc-arm-none-eabi/bin/../armrm-xilinx-eabi/usr/lib/thumb/v7+fp/hard/libc.a(lib_a-closer.o): in function `_close_r':
| (.text+0x12): undefined reference to `_close'
| /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/openamp-fw-rpc-demo/2024.2+git/recipe-sysroot-native/Vitis/2024.2/gnu/armr5/lin/gcc-arm-none-eabi/x86_64-oesdk-linux/usr/bin/arm-xilinx-eabi/arm-xilinx-eabi-ld.real: /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/openamp-fw-rpc-demo/2024.2+git/recipe-sysroot-native/Vitis/2024.2/gnu/armr5/lin/gcc-arm-none-eabi/bin/../armrm-xilinx-eabi/usr/lib/thumb/v7+fp/hard/libc.a(lib_a-openr.o): in function `_open_r':
| (.text+0x1a): undefined reference to `_open'
| /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/openamp-fw-rpc-demo/2024.2+git/recipe-sysroot-native/Vitis/2024.2/gnu/armr5/lin/gcc-arm-none-eabi/x86_64-oesdk-linux/usr/bin/arm-xilinx-eabi/arm-xilinx-eabi-ld.real: /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/openamp-fw-rpc-demo/2024.2+git/recipe-sysroot-native/Vitis/2024.2/gnu/armr5/lin/gcc-arm-none-eabi/bin/../armrm-xilinx-eabi/usr/lib/thumb/v7+fp/hard/libc.a(lib_a-readr.o): in function `_read_r':
| (.text+0x1a): undefined reference to `_read'
| collect2.real: error: ld returned 1 exit status
| make: *** [Makefile:29: executable.elf] Error 1
| ERROR: oe_runmake failed

Also if we are accessing only relative path to PWD e.g. lib/libname.a
then it would become <PREFIXMAP>/lib/libname.a and it will be a target
path which obviously will not exists on cross build host.

Hence remove -fcanon-prefix-map to fix it.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>