fpgamanager: Fix zynq7k bin file path issue
Fix zynq7k bin file path issue

ERROR: zc706-pl-demo-1.0-r0 do_compile: bootgen failed. Enable -log debug with bootgen and check logs

In Zynq7k using "-process_bitstream bin" bootgen flag, bit.bin file is
generated in XSCTH_HW_PATH directory with <xsa_name>.bit.bin file,
Hence we need to move this file from XSCTH_HW_PATH to XSCTH_WS
directory and rename to ${PN}.bit.bin for do_install task.

Also in fpgamanager_common bbclass use bootgen overwrite mode(-w) in
default bootgen flags.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>