device-tree.inc: Update XILINX_RELEASE_VERSION to v2025.1
For versal-net petalinux xsct bsps memory node is missing in the
system-top.dts and boot failed as below

ERROR: DRAM:  initcall failed at call 00000000080050b4 (err=-22)

Therefore, updated the XILINX_RELEASE_VERSION to v2025.1 for the latest
DT branch

Signed-off-by: John Vicky Vykuntapu <johnvicky.vykuntapu@amd.com>
Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>