layer.conf : Add meta-python as a layer depedency
Attempting to build this layer results in the following error:

ERROR: Nothing PROVIDES 'python3-pyyaml-native'. Close matches:
  python3-rpm-native
  python3-pycurl-native
  python3-pygpgme-native
ERROR: Required build target 'core-image-minimal' has no buildable
providers.
Missing or unbuildable dependency chain was: ['core-image-minimal',
'virtual/bootloader', 'virtual/dtb', 'python3-pyyaml-native']

To fix this, explain that the layer depends on meta-python for this
recipe.

Signed-off-by: Mike Looijmans <mike.looijmans@topic.nl>
Signed-off-by: Manjukumar Matha <manjukumar.harthikote-matha@xilinx.com>