bitstream-microblaze: Fix build errors for compile task
Below errors are observed with do_compile task.

ERROR: bitstream-microblaze-1.0+2026.1-r0 do_compile: ExecutionError('/scratch/sandeep/yocto/2026.1/yp-edf/build-plnx/tmp/work/microblazeel-v11.0-bs-cmp-re-mh-div-fb-amd-linux/bitstream-microblaze/1.0+2026.1/temp/run.do_compile.1328922', 127, None, None)
ERROR: Logfile of failure stored in: /scratch/sandeep/yocto/2026.1/yp-edf/build-plnx/tmp/work/microblazeel-v11.0-bs-cmp-re-mh-div-fb-amd-linux/bitstream-microblaze/1.0+2026.1/temp/log.do_compile.1328922
Log data follows:
| DEBUG: Executing shell function do_compile
| updatemem -meminfo /scratch/sandeep/yocto/2026.1/yp-edf/build-plnx/tmp/work/microblazeel-v11.0-bs-cmp-re-mh-div-fb-amd-linux/bitstream-microblaze/1.0+2026.1/recipe-sysroot/boot/bitstream/system.mmi -bit /scratch/sandeep/yocto/2026.1/yp-edf/build-plnx/tmp/work/microblazeel-v11.0-bs-cmp-re-mh-div-fb-amd-linux/bitstream-microblaze/1.0+2026.1/recipe-sysroot/boot/bitstream/system.bit -data /scratch/sandeep/yocto/2026.1/yp-edf/build-plnx/tmp/work/microblazeel-v11.0-bs-cmp-re-mh-div-fb-amd-linux/bitstream-microblaze/1.0+2026.1/recipe-sysroot/boot/fs-boot.elf -proc kc705_i/microblaze_0 -out /scratch/sandeep/yocto/2026.1/yp-edf/build-plnx/tmp/work/microblazeel-v11.0-bs-cmp-re-mh-div-fb-amd-linux/bitstream-microblaze/1.0+2026.1/build/download.bit
| WARNING: /scratch/sandeep/yocto/2026.1/yp-edf/build-plnx/tmp/work/microblazeel-v11.0-bs-cmp-re-mh-div-fb-amd-linux/bitstream-microblaze/1.0+2026.1/temp/run.do_compile.1328922:142 exit 127 from 'updatemem -meminfo ${MMI} -bit ${BIT} -data ${DATA} -proc ${PROCESSOR} -out ${OUT}'
| WARNING: Backtrace (BB generated script):
| /scratch/sandeep/yocto/2026.1/yp-edf/build-plnx/tmp/work/microblazeel-v11.0-bs-cmp-re-mh-div-fb-amd-linux/bitstream-microblaze/1.0+2026.1/temp/run.do_compile.1328922: line 142: updatemem: command not found
| 	#1: do_compile, /scratch/sandeep/yocto/2026.1/yp-edf/build-plnx/tmp/work/microblazeel-v11.0-bs-cmp-re-mh-div-fb-amd-linux/bitstream-microblaze/1.0+2026.1/temp/run.do_compile.1328922, line 142
| 	#2: main, /scratch/sandeep/yocto/2026.1/yp-edf/build-plnx/tmp/work/microblazeel-v11.0-bs-cmp-re-mh-div-fb-amd-linux/bitstream-microblaze/1.0+2026.1/temp/run.do_compile.1328922, line 159
ERROR: Task (/scratch/sandeep/yocto/2026.1/yp-edf/sources/poky/../meta-xilinx-tools/recipes-bsp/bitstream/bitstream-microblaze_1.0.bb:do_compile) failed with exit code '1'

This is due to updatemem tool was set incorrect with recent changes in
xsct-tc.

1. Add xsct-native to DEPENDS and set the TOOL_PATH to
   SDK toolchain.
2. Fix MMI, BIT and DATA File path to match with deployed files.
3. Remove hard coded PROC instance path and add function to read the
   processor instance path from MMI file and setVar to PROC variable.
4. Fix grammar in SUMMARY and DESCRIPTION section.

AI-Generated: GitHub Copilot (Claude Sonnet 4.5)

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Message-ID: <20260129205212.1754456-1-sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>