dfx_dtg*: Use removeprefix instead of lstrip
For example if your fw input file name is fixed_hw_1.xsa lstrip takes
the string containing set of whitespace characters to be stripped and
also it will strip all leading f,i,l,e, / and / characters from the
filename which results in below errors.

ERROR: vek280-cxe-dfx-full-1.0-r0 do_configure: ExecutionError('/scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/temp/run.do_configure.950476', 1, None, None)
ERROR: Logfile of failure stored in: /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/temp/log.do_configure.950476
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/../meta-xilinx-tools/recipes-utils/xsct/xsct-native.bb:do_populate_sysroot', '/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/../meta-xilinx/meta-xilinx-core/recipes-bsp/device-tree/device-tree.bb:do_populate_sysroot', '/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/meta/recipes-devtools/quilt/quilt-native_0.67.bb:do_populate_sysroot', 'virtual:native:/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/../meta-xilinx/meta-xilinx-core/recipes-devtools/bootgen/bootgen_2025.1.bb:do_populate_sysroot', 'virtual:native:/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', 'virtual:native:/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native:/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/meta/recipes-devtools/python/python3-pyyaml_6.0.1.bb:do_populate_sysroot', 'virtual:native:/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/meta/recipes-devtools/python/python3_3.12.9.bb:do_populate_sysroot', 'virtual:native:/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/meta/recipes-kernel/dtc/dtc_1.7.0.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['xsct-native', 'device-tree', 'gettext-minimal-native', 'cmake-native', 'libtool-native', 'm4-native', 'quilt-native', 'texinfo-dummy-native', 'libyaml-native', 'util-linux-libuuid-native', 'bootgen-native', 'openssl-native', 'expat-native', 'ncurses-native', 'zlib-native', 'flex-native', 'gnu-config-native', 'libedit-native', 'make-native', 'patch-native', 'perl-native', 'pseudo-native', 'python3-build-native', 'python3-cython-native', 'python3-flit-core-native', 'python3-installer-native', 'python3-packaging-native', 'python3-pyproject-hooks-native', 'python3-pyyaml-native', 'python3-setuptools-native', 'python3-wheel-native', 'python3-native', 'bzip2-native', 'libnsl2-native', 'libtirpc-native', 'unzip-native', 'xz-native', 'zstd-native', 'dtc-native', 'attr-native', 'gdbm-native', 'libffi-native', 'sqlite3-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_configure
| MISC_ARG is  -hdf_type xsa -hwpname vek280-cxe-dfx-full -yamlconf /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/vek280-cxe-dfx-full.yaml
| APP_ARG is
| Using xsct from: /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/recipe-sysroot-native/Vitis/2025.1/bin/xsct
| cmd is: xsct -sdx -nodisp /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/dtgen_dfx.tcl -ws /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/build -pname vek280-cxe-dfx-full -rp /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/git -processor_ip psv_cortexa72 -hdf /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/xed_hw_1.xsa -arch 64    -hdf_type xsa -hwpname vek280-cxe-dfx-full -yamlconf /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/vek280-cxe-dfx-full.yaml
|
| ****** Software Commandline Tool (XSCT) v2025.1.0
|   **** SW Build 6120661 on Tue Apr 29 11:58:05 MDT 2025
|     ** Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
|     ** Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
|
|
| Warning: XSCT is deprecated and will be removed in future releases.
| We recommend using the new Python command-line tool for project management and debugging:
| - Run "vitis -i" for interactive mode.
| - Run "vitis -s <script>" for script mode.
| WARNING: Failed in finding /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/recipe-sysroot-native/Vitis/2025.1/data/system-device-tree-xlnx/device_tree/data/device_tree.tcl path.
| WARNING: sdtgen package cannot be loaded. System Device tree commands will not
|
| be available
| INFO: [Hsi 55-2053] elapsed time for repository (/scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/recipe-sysroot-native/Vitis/2025.1/data/embeddedsw) loading 0 seconds
| Invalid workspace. set workspace using setws command
|     while executing
| "error "Invalid workspace. set workspace using setws command""
|     (procedure "check_sdk_workspace" line 4)
|     invoked from within
| "check_sdk_workspace"
|     (procedure "getsdkchan" line 7)
|     invoked from within
| "getsdkchan"
|     (procedure "::sdk::getprojects" line 19)
|     invoked from within
| "::sdk::getprojects"
|     (procedure "get_hw" line 10)
|     invoked from within
| "get_hw [lindex $args 0]"
|     (procedure "openhw" line 14)
|     invoked from within
| "openhw $hw_design"
|     (procedure "getprocessors" line 15)
|     invoked from within
| "getprocessors $params(hdf)"
|     invoked from within
| "if { $params(ws) ne "" } {
| 	# Local Work Space available
| 	if { $params(pname) ne "" } {
| 		# hwpname/bspname is empty then default it to pname+_hwproj/..."
|     (file "/scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/dtgen_dfx.tcl" line 109)
| WARNING: /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/temp/run.do_configure.950476:175 exit 1 from 'eval xsct -sdx -nodisp /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/dtgen_dfx.tcl -ws /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/build -pname vek280-cxe-dfx-full -rp /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/git -processor_ip psv_cortexa72 -hdf /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/xed_hw_1.xsa -arch 64 ${APP_ARG} ${MISC_ARG}'
| WARNING: Backtrace (BB generated script):
| 	#1: do_configure, /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/temp/run.do_configure.950476, line 175
| 	#2: main, /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/versal_vek280_xsct_seg-amd-linux/vek280-cxe-dfx-full/1.0/temp/run.do_configure.950476, line 192
ERROR: Task (/wrk/yocto_dev/sandeep/github-int/yocto/meta-bsp-dev/recipes-firmware/vek280-cxe-dfx-full/vek280-cxe-dfx-full.bb:do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1226 tasks of which 1141 didn't need to be rerun and 1 failed.

Hence use removeprefix instead of lstrip string method.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>