dfx_dtg_common.bbclass: Fix fw recipe build errors
firmware recipes build errors are observed.

ERROR: vck190-dfx-static-1.0-r0 do_configure: ExecutionError('/scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/vck190-dfx-static/1.0/temp/run.do_configure.3050253', 127, None, None)
ERROR: Logfile of failure stored in: /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/vck190-dfx-static/1.0/temp/log.do_configure.3050253
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['/scratch/sandeep/yocto/2024.2/yp-dev/sources/poky/../meta-xilinx/meta-xilinx-core/recipes-bsp/device-tree/device-tree.bb:do_populate_sysroot', '/scratch/sandeep/yocto/2024.2/yp-dev/sources/poky/meta/recipes-devtools/quilt/quilt-native_0.67.bb:do_populate_sysroot', 'virtual:native:/scratch/sandeep/yocto/2024.2/yp-dev/sources/poky/../meta-xilinx/meta-xilinx-core/recipes-devtools/bootgen/bootgen_2024.1.bb:do_populate_sysroot', 'virtual:native:/scratch/sandeep/yocto/2024.2/yp-dev/sources/poky/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', 'virtual:native:/scratch/sandeep/yocto/2024.2/yp-dev/sources/poky/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native:/scratch/sandeep/yocto/2024.2/yp-dev/sources/poky/meta/recipes-devtools/python/python3_3.12.4.bb:do_populate_sysroot', 'virtual:native:/scratch/sandeep/yocto/2024.2/yp-dev/sources/poky/meta/recipes-kernel/dtc/dtc_1.7.0.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['device-tree', 'gettext-minimal-native', 'cmake-native', 'libtool-native', 'm4-native', 'quilt-native', 'texinfo-dummy-native', 'bootgen-native', 'openssl-native', 'expat-native', 'ncurses-native', 'util-linux-libuuid-native', 'zlib-native', 'flex-native', 'gnu-config-native', 'libedit-native', 'make-native', 'patch-native', 'perl-native', 'pseudo-native', 'python3-native', 'bzip2-native', 'libnsl2-native', 'libtirpc-native', 'xz-native', 'zstd-native', 'dtc-native', 'attr-native', 'gdbm-native', 'libffi-native', 'sqlite3-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_configure
| MISC_ARG is  -hdf_type xsa -hwpname vck190-dfx-static -yamlconf /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/vck190-dfx-static/1.0/vck190-dfx-static.yaml
| APP_ARG is
| Using xsct from:
| cmd is: xsct -sdx -nodisp /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/vck190-dfx-static/1.0/dtgen_dfx.tcl -ws /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/vck190-dfx-static/1.0/build -pname vck190-dfx-static -rp /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/vck190-dfx-static/1.0/git -processor_ip psv_cortexa72 -hdf /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/vck190-dfx-static/1.0/vck190_pl_demo_static.xsa -arch 64    -hdf_type xsa -hwpname vck190-dfx-static -yamlconf /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/vck190-dfx-static/1.0/vck190-dfx-static.yaml
| /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/vck190-dfx-static/1.0/temp/run.do_configure.3050253: line 175: xsct: command not found
| WARNING: /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/vck190-dfx-static/1.0/temp/run.do_configure.3050253:175 exit 127 from 'eval xsct -sdx -nodisp /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/vck190-dfx-static/1.0/dtgen_dfx.tcl -ws /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/vck190-dfx-static/1.0/build -pname vck190-dfx-static -rp /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/vck190-dfx-static/1.0/git -processor_ip psv_cortexa72 -hdf /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/vck190-dfx-static/1.0/vck190_pl_demo_static.xsa -arch 64 ${APP_ARG} ${MISC_ARG}'
| WARNING: Backtrace (BB generated script):
| 	#1: do_configure, /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/vck190-dfx-static/1.0/temp/run.do_configure.3050253, line 175
| 	#2: main, /scratch/sandeep/yocto/2024.2/yp-dev/build-versal/tmp/work/vck190_versal-xilinx-linux/vck190-dfx-static/1.0/temp/run.do_configure.3050253, line 192
ERROR: Task (/wrk/yocto_dev/sandeep/github-int/yocto/meta-bsp-dev/recipes-firmware/vck190-dfx-static/vck190-dfx-static.bb:do_configure) failed with exit code '1'

This is due to missing xsct-native depedencies. Hence add xsct-native
dependency to fix errors.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>